---
- name: Add HHVM repo key
  shell: wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | sudo apt-key add -

- name: Add HHVM repo
  shell: echo deb http://dl.hhvm.com/ubuntu {{ ansible_distribution_release }} main | sudo tee /etc/apt/sources.list.d/hhvm.list

- name: Update apt
  apt: update_cache=yes

- name: Install HHVM and php5-cli (for command-line php)
  apt: pkg=hhvm state=latest
