---
- name: Add Percona MySql-Repository
  sudo: yes
  apt_repository: repo='deb http://repo.percona.com/apt {{ ansible_distribution_release }} main' state=present

- name: Add Key for Percona MySql Repository
  sudo: yes
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1C4CBDCDCD2EFD2A

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Percona MySql | Install Percona MySql Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - percona-server-server-5.6
    - percona-server-client-5.6
